In [ ]:
#importando a ferramenta que irá criar a representação numérica 
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
#Criando um corpus de documentos que será usado para a criação do vocabulário 
documentos = [
    "Gato e cachorro",
    "Gato brinca com cachorro",
    "gato e rato",
    "Cachorro, gato e rato",
    "gato",
    "Cachorro e rato"
]


In [10]:
#Criando um documento para ser utlizado: transformar os documentos em vetores 
vectorizer = CountVectorizer()

In [11]:
#Criando a matriz de contagem 
x = vectorizer.fit_transform(documentos)
#fit >> cria um dicionário de palavras 
#transform >> conta a frequeência de cada palavra no corpus 

In [12]:
# imprimindo a matriz e o vocabulário formado 
print(f"Vocabulário: {vectorizer.vocabulary_}")
#realiza o mapemaneto do vocabulário para um ídice da matriz

Vocabulário: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}


In [13]:
print("Matriz Bow:")
print(x.toarray())
#mostra a frequência de cada palavra no array 

Matriz Bow:
[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]
 [0 1 0 1 1]
 [0 0 0 1 0]
 [0 1 0 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

#Criando um modelo TF-IDF
vectorizer_tfidf = TfidfVectorizer()
#realiza a instaciação da classe em objeto 
X_tfidf = vectorizer_tfidf.fit_transform(documentos)
#fit >> realizar a transformaçãod o vocabulário 
#transform >> transforma cada vetor do documento com a contagemde frequência ponderada 

In [15]:
#Imprimindo o vocabulário da matriz TF-IDF
print(f"\nVocabulário TF_IDF: {vectorizer_tfidf.vocabulary_}")
print("matriz TF_IDF")
print(X_tfidf.toarray())


Vocabulário TF_IDF: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}
matriz TF_IDF
[[0.         0.75684411 0.         0.65359543 0.        ]
 [0.61845922 0.36690659 0.61845922 0.31685319 0.        ]
 [0.         0.         0.         0.59485466 0.80383327]
 [0.         0.56726902 0.         0.48988217 0.66198287]
 [0.         0.         0.         1.         0.        ]
 [0.         0.65069558 0.         0.         0.7593387 ]]
